spring:
  application:
    name: funding-service
  config:
    import: configserver:http://${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8888}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/petify
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8020

# Konfiguracja Eureka
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# Konfiguracja płatności
payment:
  stripe:
    api-key: ${stripe.secret_key}
    publishable-key: ${stripe.publishable_key}
    webhook-secret: ${stripe.webhook_secret}
    enabled: true
    api-version: "2023-10-16"
  payu:
    client-id: ${payu.client_id:}
    client-secret: ${payu.client_secret:}
    pos-id: ${payu.pos_id:}
    md5-key: ${payu.md5_key:}
    api-url: https://secure.snd.payu.com
    enabled: true
    sandbox-mode: true
  analytics:
    enabled: true
    retention-days: 365
    aggregation-schedule: "0 0 1 * * ?"

# Webhook base URL
app:
  webhook:
    base-url: http://${APP_HOST:localhost}:${APP_PORT:8020}
