server:
  port: 9000

spring:
  security:
    oauth2:
      authorization-server:
        issuer-url: http://auth-service:9000
      client:
        registration:
          google:
            client-id: ${google.client.id}
            client-secret: ${google.client.secret}
            scope:
              - email
              - profile
            redirect-uri: "http://localhost:9000/login/oauth2/code/google"


  datasource:
    url: jdbc:postgresql://localhost:5433/petify
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect