server:
  port: 9000

spring:
  security:
    oauth2:
      authorization-server:
        issuer-url: http://auth-service:9000

  datasource:
    url: jdbc:postgresql://localhost:5433/petify
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect