server:
  port: 8020

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5433}/${PGDATABASE:petify}
    username: ${PGUSER:admin}
    password: ${PGPASSWORD:admin}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:9000}/.well-known/jwks.json

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

payment:
  stripe:
    api-key: ${STRIPE_SECRET_KEY:${stripe.secret.key}}
    publishable-key: ${STRIPE_PUBLISHABLE_KEY:${stripe.publishable.key}}
    webhook-secret: ${STRIPE_WEBHOOK_SECRET:${stripe.webhook.secret}}
    enabled: true
    api-version: "2023-10-16"

  payu:
    # PayU Sandbox credentials
    default-customer-ip: "127.0.0.1"
    client-id: ${PAYU_CLIENT_ID:300746}
    client-secret: ${PAYU_CLIENT_SECRET:2ee86a66e5d97e3fadc400c9f19b065d}
    pos-id: ${PAYU_POS_ID:300746}
    md5-key: ${PAYU_MD5_KEY:b6ca15b0d1020e8094d9b5f8d163db54}
    api-url: ${PAYU_API_URL:https://secure.snd.payu.com}
    enabled: true
    sandbox-mode: true

  analytics:
    enabled: true
    retention-days: 365
    aggregation-schedule: "0 0 1 * * ?" # Daily at 1 AM

app:
  webhook:
    base-url: ${WEBHOOK_BASE_URL:http://localhost:8222}

logging:
  level:
    org.petify.funding: DEBUG
    org.springframework.security: DEBUG
    com.stripe: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health
