server:
  port: 8222

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: shelter-service
          uri: lb://SHELTER-SERVICE
          predicates:
            - Path=/shelters/**, /shelters, /pets/**, /pets
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/oauth2/**, /auth/**, /admin/**, /user/**