server:
  port: 8222

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "Authorization"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**, /admin/**, /user/**, /volunteer/**
          filters:
            - PreserveHostHeader

        - id: auth-service-oauth
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/oauth2/**, /login/oauth2/code/**
          filters:
            - PreserveHostHeader

        - id: shelter-service
          uri: lb://SHELTER-SERVICE
          predicates:
            - Path=/shelters/**, /shelters, /pets/**, /pets, /adoptions/**, /adoptions
          filters:
            - PreserveHostHeader

        - id: reservations-service
          uri: lb://RESERVATIONS-SERVICE
          predicates:
            - Path=/reservations/**, /reservations
          filters:
            - PreserveHostHeader

        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/ws-chat/**, /chat/**
          filters:
            - PreserveHostHeader

        - id: funding-service
          uri: lb://FUNDING-SERVICE
          predicates:
            - Path=/donations/**, /donations, /payments/**, /payments, /fundraisers/**, /fundraisers
          filters:
            - PreserveHostHeader

        - id: image-service
          uri: lb://IMAGE-SERVICE
          predicates:
            - Path=/images/**, /images
          filters:
            - PreserveHostHeader

        - id: feed-service
          uri: lb://FEED-SERVICE
          predicates:
            - Path=/posts/**, /posts, /events/**, /events
          filters:
            - PreserveHostHeader

# Konfiguracja Eureka
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: ${GATEWAY_HOST:localhost}
