server:
  port: 8222

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "Authorization"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - PreserveHostHeader
            - AddRequestHeader=X-Forwarded-Prefix, /users

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/oauth2/**, /auth/**, /admin/**, /user/**
          filters:
            - PreserveHostHeader

        - id: shelter-service
          uri: lb://SHELTER-SERVICE
          predicates:
            - Path=/shelters/**, /shelters, /pets/**, /pets, /adoptions/**, /adoptions
          filters:
            - PreserveHostHeader

# Konfiguracja Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: localhost