server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/.well-known/jwks.json

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    # Zwiększamy timeout dla rejestracji
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
    # Upewniamy się, że usługa regularnie wysyła heartbeat
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10