version: '3.8'

services:
  postgres-dev:
    image: postgres:latest
    container_name: postgres-db-dev
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "petify"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev: