export JWT_ADMIN="eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjkwMDAiLCJzdWIiOiJkY2xydDExdjRsenppZmF1LWFkbWluIiwiYXV0aF9tZXRob2QiOiJmb3JtIiwiZXhwIjoxNzUwNTgzNzUzLCJpYXQiOjE3NTA0OTczNTMsInJvbGVzIjpbIkFETUlOIiwiVVNFUiJdfQ.CORnTQpnMa9G61hwSJcpQ4f_qTeTPCbVZmV7w1PwgMDllLUjWu7ry_KtpTidJW3heSLU-xTmhINNlMrXhfRadOcnYqlaDOWN4iU-iDeIQNoZYHqbaBeKpPYk4_LvyGm4_uaa23YUgE8UkfGkSf0LXENiAyehHbvBIofbkHTyqRRE4P6AAgXckBzx0C5kfvXPhfdoMucLIad5bT7GKmBiTRk920NUdyIaZddsHYJ6nEAGLuajjNh3jjInUgLFsXuLUK5AiWUYdd6BV84IhKpD885Q1Jmq2PQO41BKgJb4Qxs38l90EHcVO63lNJslCDFF6Zw_SZrSWAicIr5TRVBgIA"
export BASE_URL="http://localhost:8222"

python3 tools/db_loaders/shelter_loader.py
python3 tools/db_loaders/pet_loader.py
python3 tools/db_loaders/volunteer_loader.py
python3 tools/db_loaders/funding_loader.py
python3 tools/db_loaders/feed_loader.py
