x-common-variables: &common-variables
  SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
  SPRING_DATASOURCE_USERNAME: ${DB_USER}
  SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

  AUTH_SERVICE_PORT: 9000
  AUTH_SERVICE_HOST: auth-server
  CONFIG_SERVER_PORT: 8888
  CONFIG_SERVER_HOST: config-server
  EUREKA_PORT: 8761
  EUREKA_HOST: discovery

  GATEWAY_URL: http://gateway:8222

services:
  postgres:
    image: bitnami/postgresql:17
    entrypoint: ["sleep", "infinity"]
    environment:
      PGPORT: ${DB_PORT}
      PGHOST: ${DB_HOST}
      PGDATABASE: ${DB_NAME}
      PGUSER: ${DB_USER}
      PGPASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h ${DB_HOST} -p ${DB_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    mem_limit: 128m

  config-server:
    image: ${ACR_LOGIN_SERVER}/petify-config-server:latest
    expose:
      - 8888
    environment:
      <<: *common-variables
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      retries: 10
    mem_limit: 1g

  discovery:
    image: ${ACR_LOGIN_SERVER}/petify-discovery:latest
    expose:
      - 8761
    environment:
      <<: *common-variables
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 15s
      retries: 20
    mem_limit: 1g

  auth-server:
    image: ${ACR_LOGIN_SERVER}/petify-auth-server:latest
    expose:
      - 9000
    environment:
      <<: *common-variables
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    depends_on:
      discovery:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/actuator/health"]
      interval: 15s
      retries: 20
    mem_limit: 1g

  # chat:
  #   image: ${ACR_LOGIN_SERVER}/petify-chat:latest
  #   expose:
  #     - 8050
  #   environment:
  #     <<: *common-variables
  #   depends_on:
  #     discovery:
  #       condition: service_healthy
  #     postgres:
  #       condition: service_healthy
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8050/actuator/health"]
  #     interval: 15s
  #     retries: 10
  #     start_period: 30s
  #   mem_limit: 1g

  feed:
    image: ${ACR_LOGIN_SERVER}/petify-feed:latest
    expose:
      - 8030
    environment:
      <<: *common-variables
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
    depends_on:
      discovery:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8030/actuator/health"]
      interval: 15s
      retries: 20
    mem_limit: 1g

  funding:
    image: ${ACR_LOGIN_SERVER}/petify-funding:latest
    expose:
      - 8020
    environment:
      <<: *common-variables
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      PAYU_CLIENT_ID: ${PAYU_CLIENT_ID}
      PAYU_CLIENT_SECRET: ${PAYU_CLIENT_SECRET}
      PAYU_POS_ID: ${PAYU_POS_ID}
      PAYU_MD5_KEY: ${PAYU_MD5_KEY}
      PAYU_API_URL: ${PAYU_API_URL}
      WEBHOOK_BASE_URL: http://gateway:8222
    depends_on:
      discovery:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8020/actuator/health"]
      interval: 15s
      retries: 20
    mem_limit: 1g

  image:
    image: ${ACR_LOGIN_SERVER}/petify-image:latest
    expose:
      - 8060
    environment:
      <<: *common-variables
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
    depends_on:
      discovery:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8060/actuator/health"]
      interval: 15s
      retries: 20
    mem_limit: 1g

  reservations:
    image: ${ACR_LOGIN_SERVER}/petify-reservations:latest
    expose:
      - 8011
    environment:
      <<: *common-variables
    depends_on:
      discovery:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8011/actuator/health"]
      interval: 15s
      retries: 20
    mem_limit: 1g

  shelter:
    image: ${ACR_LOGIN_SERVER}/petify-shelter:latest
    expose:
      - 8010
    environment:
      <<: *common-variables
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
    depends_on:
      discovery:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8010/actuator/health"]
      interval: 15s
      retries: 20
    mem_limit: 1g

  gateway:
    image: ${ACR_LOGIN_SERVER}/petify-gateway:latest
    ports:
      - 8222:8222
    environment:
      <<: *common-variables
    depends_on:
      discovery:
        condition: service_healthy
      auth-server:
        condition: service_healthy
      # chat:
      #   condition: service_healthy
      feed:
        condition: service_healthy
      funding:
        condition: service_healthy
      image:
        condition: service_healthy
      reservations:
        condition: service_healthy
      shelter:
        condition: service_healthy
    mem_limit: 1g
