spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8888}

logging:
  level:
    org.springframework.cloud.gateway: TRACE