spring:
  application:
    name: shelter-service
  config:
    import: configserver:http://${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8888}

s3:
  access-key: ${s3.access.key}
  secret-key: ${s3.secret.key}